// <auto-generated />
using FullStackAssessment.Api.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FullStackAssessment.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260706105939_SeedInitialInventoryData")]
    partial class SeedInitialInventoryData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FullStackAssessment.Api.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ProductTypeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProductTypeId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "High-performance GPU for gaming and rendering.",
                            Name = "Graphics Card",
                            Price = 899.99m,
                            ProductTypeId = 1
                        },
                        new
                        {
                            Id = 2,
                            Description = "Ergonomic office chair with lumbar support.",
                            Name = "Office Chair",
                            Price = 199.99m,
                            ProductTypeId = 2
                        },
                        new
                        {
                            Id = 3,
                            Description = "Mechanical RGB tactile keyboard.",
                            Name = "Keyboard",
                            Price = 49.99m,
                            ProductTypeId = 1
                        },
                        new
                        {
                            Id = 4,
                            Description = "High-precision wireless gaming mouse.",
                            Name = "Gaming Mouse",
                            Price = 59.99m,
                            ProductTypeId = 1
                        },
                        new
                        {
                            Id = 5,
                            Description = "Legacy hardware inventory item.",
                            Name = "Obsolete Item",
                            Price = 5.00m,
                            ProductTypeId = 3
                        },
                        new
                        {
                            Id = 999,
                            Description = "Generic placeholder data for system testing.",
                            Name = "Ghost Product",
                            Price = 0.00m,
                            ProductTypeId = 3
                        });
                });

            modelBuilder.Entity("FullStackAssessment.Api.Models.ProductType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ProductTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Electronics"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Furniture"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Miscellaneous"
                        });
                });

            modelBuilder.Entity("FullStackAssessment.Api.Models.Product", b =>
                {
                    b.HasOne("FullStackAssessment.Api.Models.ProductType", "ProductType")
                        .WithMany("Products")
                        .HasForeignKey("ProductTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProductType");
                });

            modelBuilder.Entity("FullStackAssessment.Api.Models.ProductType", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
